name: Daily analytics digest
on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"
jobs:
  ytStats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        # install dependencies for scraper script
        run: npm ci
        working-directory: ./sh/fetch-yt-stats
      - name: Fetch youtube analytics for today
        run: |
          mkdir -p "./_data/"
          cat "./_data/yt-stats.json" | \
          node ./sh/fetch-yt-stats/ > \
          "./_data/yt-stats.json"
      - name: Set up git config
        # commit as a made up bot user
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: Commit
        # if there are changes commit and push
        run: |
          git add .
          # only commit if there's a change
          git diff --quiet --staged || git commit -m "Updated: Youtube Analytics $(date -d yesterday +"%Y-%m-%d")"
          git push origin master
